name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Maven package
      if: ${{ job.status == 'success' }}
      run: mvn clean install
    - name: Build with Maven
      if: ${{ job.status == 'success' }}
      run: mvn -B package --file pom.xml
    - name: Run tests
      if: ${{ job.status == 'success' }}
      run: mvn test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Merge to main and create pull request
      if: ${{ job.status == 'success' }}
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Merge develop to main',
            head: 'develop',
            base: 'main',
            body: 'This pull request merges changes from the develop branch to the main branch.',
          });

          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.data.number,
            commit_title: 'Automerge changes from develop to main',
          });